verify_plugin_signatures: false

# We ignore the following git hooks provided by overcommit for now
PostCheckout:
  ALL:
    enabled: false
CommitMsg:
  ALL:
    enabled: false

# Custom options for Iris repository
PreCommit:
  # Ignore all Overcommit default options
  ALL:
    enabled: false
    on_warn: fail

  # Enable explicitly each desired pre commit check
  Rubocop:
    enabled: true
    description: 'Analyzing with Rubocop'
    required_executable: 'rubocop'

  TrailingWhitespace:
    enabled: true
    description: 'Checking for trailing whitespace'
    exclude:
      - 'spec/cassettes/**/*.yml'
      - 'app/assets/**/*.svg'

  RailsSchemaUpToDate:
    enabled: true
    description: 'Checking if database schema is up to date'
    include:
      - 'db/migrate/*.rb'
      - 'db/schema.rb'
      - 'db/structure.sql'

  YamlSyntax:
    enabled: true
    description: 'Checking YAML syntax'

  JsHint:
    enabled: true
    description: 'Analyzing with JSHint'
    required_executable: 'jshint'
    install_command: 'npm install -g jshint'

  Jscs:
    enabled: true
    description: 'Analyzing with JSCS'
    required_executable: 'jscs'
    install_command: 'npm install -g jscs'

  RailsBestPractices:
    enabled: true
    description: 'Checking Rails best practices'
