AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - 'lib/tasks/**/*'
  Exclude:
    - Gemfile*
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/bundle/**/*'
  RunRailsCops: true

# We don't care about method length, since we check method cyclomatic
# complexity.
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

# Trailing commas make for clearer diffs because the last line won't appear
# to have been changed, as it would if it lacked a comma and had one added.
Style/TrailingComma:
  EnforcedStyleForMultiline: comma

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    # Using `[]` for string arrays instead of `()`, since normal arrays are
    # indicated with `[]` not `()`.
    '%w': '[]'
    '%W': '[]'

Style/AndOr:
  # Whether `and` and `or` are banned only in conditionals (conditionals)
  # or completely (always).
  # They read better, more like normal English.
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*'
