default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: iris_development

test:
  <<: *default
  database: iris_test

production:
  <<: *default
  database: iris_production
