AddModelVirtualAttributeCheck: { }
AlwaysAddDbIndexCheck: { }
CheckSaveReturnValueCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
HashSyntaxCheck: { }
IsolateSeedDataCheck: { }
KeepFindersOnTheirOwnModelCheck: { }
LawOfDemeterCheck: { }
# Rubocop already runs this check
#LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 2 }
MoveFinderToNamedScopeCheck: { }
MoveModelLogicIntoModelCheck: { use_count: 4 }
NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
NotUseTimeAgoInWordsCheck: { }
OveruseRouteCustomizationsCheck: { customize_count: 3 }
ProtectMassAssignmentCheck: { }
RemoveEmptyHelpersCheck: { }
RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: { }
RemoveUnusedMethodsInControllersCheck:
  # We exclude setter methods because this case is not working properly
  # https://github.com/railsbp/rails_best_practices/issues/225
  #
  # We also ignore warnings related with ApplicationController#render
  # because it is overrided but it's used by Rails internal code
  except_methods: [
    'ApplicationController#render',
    'ApplicationController#after_sign_out_path_for',
    '*#=$',
    '*#model_params',
    'RegistrationsController#after_update_path_for',
    'RegistrationsController#build_resource',
    'RegistrationsController#after_inactive_sign_up_path_for'
  ]
RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }
RemoveUnusedMethodsInModelsCheck:
  except_methods: [
    '#table_name_prefix'
  ]
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
ReplaceInstanceVariableWithLocalVariableCheck: { }
# This check does not property look at inherited controller methods
# RestrictAutoGeneratedRoutesCheck: { }
SimplifyRenderInControllersCheck: { }
# This check cannot handle the situation where:
# a partial is used, a collection is given, and locals are given.
# http://rails-bestpractices.com/posts/2010/12/04/simplify-render-in-views/
# See most recent comments.
SimplifyRenderInViewsCheck: {
  ignored_files: 'app/views/conversations/index.html.haml'
}

# This check does not seem to work with inherited controller filters
# Additional info:
# http://rails-bestpractices.com/posts/2010/07/24/use-before_filter
# UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: { }
UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }
UseQueryAttributeCheck: { }
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }
AvoidSendMethodCheck: { }
AvoidRailsEnvCheck: { ignored_files: ['config'] }
